# Generated by Django 3.2.7 on 2021-09-20 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tag_tag_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='tag',
        ),
        migrations.AddField(
            model_name='photo',
            name='tag',
            field=models.ManyToManyField(to='api.Tag', verbose_name='Tag'),
        ),
    ]
