# Generated by Django 3.2.7 on 2021-09-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=100)),
                ('game_create', models.CharField(max_length=100)),
                ('ships_creator', models.TextField(max_length=200)),
                ('game_opponent', models.CharField(blank=True, max_length=100, null=True)),
                ('ships_opponent', models.TextField(max_length=200)),
                ('is_over', models.BooleanField(default=False)),
            ],
        ),
    ]
