# Generated by Django 3.2.7 on 2021-09-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='ships_opponent',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
